### DISCUSSION TITLE
docs/prometheus/

### DISCUSSION THREAD

**Discussion by giscus** [ricsanfre/pi-cluster#356] [Announcements]
# docs/prometheus/

How to deploy kuberentes cluster monitoring solution based on Prometheus. Installation based on Prometheus Operator using kube-prometheus-stack project.

https://picluster.ricsanfre.com/docs/prometheus/

**Comment by i5Js** [comment]
I have had to uncheck the client authentication in the Client configuration, otherwise I have had an error after login: code_to_token_error invalid client credentials

**Reply by ricsanfre** [reply]
Client authentication has to be enabled. Otherwise, the client credentials are not created. Once the client is added to keycloak its client credentials: client_id and client_secret need to be used in the configuration: grafana config.

**Reply by i5Js** [reply]
With the new version, you can't add the client_secret to the values, otherwise, you will get: 
`Error: UPGRADE FAILED: execution error at (kube-prometheus-stack/charts/grafana/templates/deployment.yaml:36:28): Sensitive key 'auth.generic_oauth.client_secret' should not be defined explicitly in values. Use variable expansion instead. You can disable this client-side validation by changing the value of assertNoLeakedSecrets`.

So you need to create a secret like the follow:
```
apiVersion: v1
data:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: <client_secret base64 enconded>
kind: Secret
metadata:
  creationTimestamp: null
  name: grafana-env-secret
  namespace: monitoring
```
However, even with this config I have the same error message_

`2024-03-31 20:08:55,547 WARN  [org.keycloak.events] (executor-thread-137) type="CODE_TO_TOKEN_ERROR", realmId="66b4fa57-c607-4d1f-8b48-4a0a1d72c464", clientId="grafana", userId="null", ipAddress="10.244.7.1", error="invalid_client_credentials", grant_type="authorization_code"`

On the grafana pod we see:

`logger=authn.service t=2024-03-31T20:36:57.903936684Z level=error msg="Failed to authenticate request" client=auth.client.generic_oauth error="[auth.oauth.token.exchange] failed to exchange code to token: oauth2: \"unauthorized_client\" \"Invalid client or Invalid client credentials\""`

And the client, and client secrets are ok

**Reply by ricsanfre** [reply]
The use of GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET for latest releases of Grafana is already documented.

According to your logs it seems that you are not providing the proper credentials for Grafana client.

**Reply by i5Js** [reply]
Hi Ricardo, 

Yes, it seems, but the credentials are ok. Because if I disable Client authentication, the credentials works.

**Reply by i5Js** [reply]
Still having problems to login. After moving all from traefik to nginx, it still doesn't work
```

2024-04-17 08:10:23,381 WARN  [org.keycloak.events] (executor-thread-131) type="CODE_TO_TOKEN_ERROR", realmId="2bb4892c-4381-470d-bc6d-5aa45108067f", clientId="grafana", userId="d67a175d-d4ae-4d62-9070-09aa309b2ee0", ipAddress="10.244.7.0", error="not_allowed", grant_type="authorization_code", code_id="7edd0eb7-5355-46de-9345-77c4ba2c9e39", client_auth_method="client-secret"
2024-04-17 08:10:23,387 WARN  [org.keycloak.protocol.oidc.utils.OAuth2CodeParser] (executor-thread-131) Code '6e55819a-f229-4aa3-9673-00279796872e' already used for userSession '7edd0eb7-5355-46de-9345-77c4ba2c9e39' and client 'd14fa3e0-0c1f-43a5-8358-e95799ac0e99'.
2024-04-17 08:10:23,388 WARN  [org.keycloak.events] (executor-thread-131) type="CODE_TO_TOKEN_ERROR", realmId="2bb4892c-4381-470d-bc6d-5aa45108067f", clientId="grafana", userId="null", ipAddress="10.244.7.0", error="invalid_code", grant_type="authorization_code", code_id="7edd0eb7-5355-46de-9345-77c4ba2c9e39", client_auth_method="client-secret"
```

And the credentials are right

Logs from grafana pod:

`logger=authn.service t=2024-04-17T08:32:09.410902828Z level=error msg="Failed to authenticate request" client=auth.client.generic_oauth error="[auth.oauth.token.exchange] failed to exchange code to token: oauth2: \"invalid_grant\" \"Code not valid\""`

**Reply by i5Js** [reply]
FIXED! Finally! I found it checking the env variables inside the grafana pod:


```
kube-prometheus-stack-grafana-8f748478-5z7jr:/usr/share/grafana$ env | grep GF_
GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=<secret_uncoded>
GF_PATHS_HOME=/usr/share/grafana
GF_PATHS_PROVISIONING=/etc/grafana/provisioning
GF_SECURITY_ADMIN_PASSWORD=prom-operator
GF_SECURITY_ADMIN_USER=admin
GF_PATHS_DATA=/var/lib/grafana/
GF_PATHS_LOGS=/var/log/grafana
GF_PATHS_PLUGINS=/var/lib/grafana/plugins
GF_PATHS_CONFIG=/etc/grafana/grafana.ini
```

Then I have realized there was one miss: `GF_AUTH_GENERIC_OAUTH_CLIENT_ID`

And that explains why always had  **`userId="null"`**. So I modified the secret:


```
apiVersion: v1
data:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: <clientsecret_base64>
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: <clientid_base64>
kind: Secret
metadata:
  creationTimestamp: null
  name: grafana-env-secret
  namespace: monitoring
```

And restarted the pod: `kubectl -n monitoring rollout restart deployment kube-prometheus-stack-grafana`

And finally, checked the envs:


```
kube-prometheus-stack-grafana-8f748478-5z7jr:/usr/share/grafana$ env | grep GF_
GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=<secret_uncoded>
**GF_AUTH_GENERIC_OAUTH_CLIENT_ID**=grafana-oauth
GF_PATHS_HOME=/usr/share/grafana
GF_PATHS_PROVISIONING=/etc/grafana/provisioning
GF_SECURITY_ADMIN_PASSWORD=prom-operator
GF_SECURITY_ADMIN_USER=admin
GF_PATHS_DATA=/var/lib/grafana/
GF_PATHS_LOGS=/var/log/grafana
GF_PATHS_PLUGINS=/var/lib/grafana/plugins
GF_PATHS_CONFIG=/etc/grafana/grafana.ini
```
And boom! working:


```
logger=context userId=0 orgId=0 uname= t=2024-04-19T12:40:28.158783866Z level=info msg="Request Completed" method=GET path=/login/generic_oauth status=302 remote_addr=10.244.0.0 time_ms=0 duration=239.164µs size=345 referer= handler=/login/:name status_source=server
logger=oauth.generic_oauth t=2024-04-19T12:40:28.259028574Z level=debug msg="Getting user info"
logger=oauth.generic_oauth t=2024-04-19T12:40:28.259125406Z level=debug msg="Extracting user info from OAuth token"
logger=oauth.generic_oauth t=2024-04-19T12:40:28.259833854Z level=debug msg="Received id_token" raw_json="{\"exp\":1713530731,\"iat\":1713530431,\"auth_time\":1713529886,\"jti\":\"e74d1c01-a1ac-4fd8-ac49-0362be7c2021\",\"iss\":\"https://sso.home.domain.com/realms/home\",\"aud\":\"grafana-oauth\",\"sub\":\"d67a175d-d4ae-4d62-9070-09aa309b2ee0\",\"typ\":\"ID\",\"azp\":\"grafana-oauth\",\"session_state\":\"8dfd088e-7055-4c82-aa87-e1bc06868814\",\"at_hash\":\"mcxdogCSuT-NeDvnEoeExw\",\"acr\":\"0\",\"sid\":\"8dfd088e-7055-4c82-aa87-e1bc06868814\",\"email_verified\":true,\"roles\":[\"editor\",\"viewer\",\"offline_access\",\"admin\",\"default-roles-home.javisalas.com\",\"uma_authorization\"],\"name\":\"Grafana Admin\",\"preferred_username\":\"grafanadmin\",\"given_name\":\"Grafana\",\"family_name\":\"Admin\",\"email\":\"grafana@domain.com\"}" data="Name: Grafana Admin, Displayname: , Login: , Username: , Email: grafana@domain.com, Upn: , Attributes: map[]"
```

**Reply by ricsanfre** [reply]
Hi Javi,

In my Prometheus packaged application for ArgoCD, I am specifying both environment variables GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET and GF_AUTH_GENERIC_OAUTH_CLIENT_ID. That way I can configure not only the password but the client_id from a external secret defined in my Secret Manager. See External Secret definition https://github.com/ricsanfre/pi-cluster/blob/master/argocd/system/monitoring/templates/grafana-env-externalsecret.yaml

When I did manual installation tests specifying GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET as environment variable, adding GF_AUTH_GENERIC_OAUTH_CLIENT_ID was not a requirement,. client_id could be specified in the `grafana.ini` section within the values.yaml.

```yaml
grafana:
  grafana.ini:
      # SSO configuration
      auth.generic_oauth:
        enabled: true
        name: Keycloak-OAuth
        allow_sign_up: true
        client_id: grafana
```
According to Grafana's documentation the "GF_" environment variables are only overriding specific configuration parameters you have in the `grafana.ini` file. So it should not be mandatory to add both environment variables if the client_id is part of the `grafana.ini`.

Is that not working? Is it needed to a both as Grafana's environment variables in the external secret?
If it is mandatory to add both variables, I will modify the documentation.

Thanks
Regards
Ricardo

**Reply by i5Js** [reply]
Hello Ricardo, 

I made a new test: I have removed the client_id from the values files, and it's still working, so, it's not needed.

Happy to help. 

Regards

Javier.

**Reply by ricsanfre** [reply]
Hi Javi,

What I wanted to test is the opposite. Keeping client_id in the values file and removing GF_AUTH_GENERIC_OAUTH_CLIENT_ID from the secret. If that was your initial set-up, and it was not working, I will modify the documentation.

Regards
Ricardo

**Reply by i5Js** [reply]
Hi Ricardo, 

That was my initial setup, and it was not working. Perhaps, they have changed something and it's something different than client_id, but trust me, it was not working. Two weeks on this!! :) 

Cheers

Javi

**Comment by i5Js** [comment]
The Nginx Grafana dashboard doesn't work "out of the box", we need to adjust nginx settings and promethus settings described here:

https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/monitoring.md

**Reply by ricsanfre** [reply]
Hi @i5Js,

I am not finding any issue with my nginx grafana dashboard.
Prometheus ServiceMonitor resource is created by default by nginx helm chart using this configuration:

```yaml
controller:
  # Enabling Prometheus metrics and Service Monitoring
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
```

My nginx dashboard works fine without any additional prometheus configuration applied to nginx

![image](https://github.com/ricsanfre/pi-cluster/assets/84853324/b3a581b0-7b94-4ce1-a562-afa366283305)


Regards
Ricardo

**Comment by benbourner** [comment]
The Ingress for the grafana dashboard rewrites the URL to remove /grafana, but grafana is configured to be served from /grafana, so the ingress doesn't work. Commenting out these lines in the grafana ingress solves it:
```
    # Rewrite target
    # nginx.ingress.kubernetes.io/use-regex: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
```
Also no further need for the regex group match on the path:

```
    path: /grafana
```

**Reply by benbourner** [reply]
Also the metrics is being queried from Prometheus on the wrong path, `/metrics` instead of `/grafana/metrics`, resulting in a failed scraper but I have not yet figured out how to fix that 😊

**Reply by benbourner** [reply]
Solved, needs to be added so:
```
 # ServiceMonitor label and job relabel
  serviceMonitor:
    path: /grafana/metrics
    labels:
      release: kube-prometheus-stack
    relabelings:
 ...
 ```

**Reply by ricsanfre** [reply]
Hi @benbourner,

In my cluster, I have the configuration as it is stated in the guide and everything works fine. Grafana endpoint is reachable at `https://monitoring.picluster.ricsanfre.com/grafana/` and grafana metrics also are available at `/metrics` endpoint. 

Have you check whether you have this grafana configuration to make it can work behind a proxy.

```yaml
grafana:
  # Configuring grafana to run behind a proxy under a subpath
  grafana.ini:
    server:
      domain: monitoring.picluster.ricsanfre.com
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      # Running Grafana behind proxy rewrite path
      # https://grafana.com/tutorials/run-grafana-behind-a-proxy/
      serve_from_sub_path: true

```

My working ingress resource is

```yaml
# Ingress Grafana
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: monitoring
  annotations:
    # Linkerd configuration. Configure Service as Upstream
    nginx.ingress.kubernetes.io/service-upstream: "true"
    # Rewrite target
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # Enable cert-manager to create automatically the SSL certificate and store in Secret
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    cert-manager.io/common-name: monitoring.picluster.ricsanfre.com

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - monitoring.picluster.ricsanfre.com
      secretName: monitoring-tls
  rules:
    - host: monitoring.picluster.ricsanfre.com
      http:
        paths:
          - path: /grafana/(.*)
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 80
```
Please, let me know if you have followed all the steps in the guide and if you still have issues.

Regards
Ricardo

**Reply by sbatururimi** [reply]
Hi @ricsanfre and @benbourner, looks like I faced the same problem  despite following the guideline here. 
Adding the path to service monitor helped to fix the problem in prometheus to check the Grafana's status:
```
serviceMonitor:
    path: /grafana/metrics
    labels:
      release: kube-prometheus-stack
    relabelings:
```

For grafana ingress, only adjusting (commenting the regex & rewrite + adding service-upstream)  as follow helped:

```
annotations:
    # Linkerd configuration. Configure Service as Upstream
    nginx.ingress.kubernetes.io/service-upstream: "true"
    # # Rewrite target
    # nginx.ingress.kubernetes.io/use-regex: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
...
rules:
    - host: monitoring.kube.cluster1.renty.life
      http:
        paths:
          # - path: /grafana/(.*)
          - path: /grafana
```

What could be wrong that these changes was necessary for me and @benbourner?

**Reply by ricsanfre** [reply]
Hi @sbatururimi, I have detected an inconsistency between the documentation and my current grafana/prometheus working configuration.

Since rewrite rules are configured within NGINX (reverse-proxy), grafana's `server_from_sub_path` has to be set to `false`

```yaml
grafana:
  # Configuring grafana to run behind a proxy under a subpath
  grafana.ini:
    server:
      domain: monitoring.picluster.ricsanfre.com
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      # Running Grafana behind proxy rewrite path
      # https://grafana.com/tutorials/run-grafana-behind-a-proxy/
      serve_from_sub_path: false
```
With this configuration, Ingress resources should work.

I have updated documentation to fix this inconsistency.

Let me know if that works for you.

Regards
Ricardo

**Reply by sbatururimi** [reply]
In order to fix the sso issue login to grafana `Invalid parameter: redirect_uri`, I added a few modifications that looks like to be important:
1) in the values.yaml

```
root_url: "https://%(domain)s/grafana/"
```

2) in the ingress yaml I added an additional rule (I have setup keycloak for prometheus) otherwise using `<domain>/grafana` was redirecting to the next rule, which was the keycloak oauth-2 proxy for prometheus in my case:

```
http:
  paths:
    # Match `/grafana` (no trailing slash)
    - path: /grafana
      pathType: Exact
      backend:
        service:
          name: kube-prometheus-stack-grafana
          port:
            number: 80
    # Match `/grafana/` and subpaths
    - path: /grafana/(.*)
      # - path: /grafana
      pathType: ImplementationSpecific
      backend:
        service:
          name: kube-prometheus-stack-grafana
          port:
            number: 80
```

the problem was that when clicking the sso login with keycloak (`Sign in with Keycloak-OAuth) the redirect link used http and the port instead of https and no port like follow: `<other part of the redirect>/protocol/openid-connect/auth?client_id=grafana&redirect_uri=http://<my monitoring domain>:3000/grafana/login/generic_oauth`

**Reply by ricsanfre** [reply]
1) That is the proper value for `root_url` parameter to be used when integrating with Keycloak. It was already documented in the SSO section configuration: https://picluster.ricsanfre.com/docs/prometheus/#grafana-sso-configuration

2) Related to additional NGINX rule it is only needed if you do not specify the traiiling '/' character, which I always do :-).. I will test your additional rule and add it to the configuration

By the way you can find all my latest working configuration (Flux CD packaged applications) in my repo https://github.com/ricsanfre/pi-cluster. I try to keep up to date the documentation with my latest tested configuration since the new versions of the helm charts introduces modifications but sometimes I forgot to copy all the changes.
Any PR containing improvements to both the documentation and the original configuration is welcome.

Thanks

**Comment by sbatururimi** [comment]
Hi, Ricardo. Wonderful documentation in general and one of the best. In the section `What has been deployed by kube-stack?` is it the example of objects deployed during the installation or those are recommended objects to be recreated to replace those one installed by the operator?

**Reply by ricsanfre** [reply]
Thanks @sbatururimi,
That section contains sample Prometheus and AlertManager objects created automatically by kube-prom-stack helm chart that are used by the operator. Samples objects are in the doc only to explain how helm chart works. The actual objects generated will be different depending on the values provided to the helm chart and the helm chart version used.

**Reply by sbatururimi** [reply]
Thank you for the explanation!

**Comment by sbatururimi** [comment]
Looks like this is not required in newest version of grafana and part of it by default?
```
# List of grafana plugins to be installed
  plugins:
    - grafana-piechart-panel
```

**Reply by ricsanfre** [reply]
Thanks @sbatururimi for the info.
It seems that it is already included since Grafana 8.0
I will update the documentation.

**Comment by sbatururimi** [comment]
Looks like the community dashboard for ElasticSearch has been deleted.
I found it in this [old commit](https://github.com/prometheus-community/elasticsearch_exporter/blob/cb272485bb1724741ea2f2fef6eb86217c50e198/examples/grafana/dashboard.json).
But I still get some graphics broken and unworking requiring a lot of search of available metrics.
@ricsanfre could you update with that please?
Maybe most of metrics are not available and that's why or broken...

That would help  lot.

**Comment by sbatururimi** [comment]
If we add new datasources or databases how to have them back if the pod is grafana recreated?
In docker, generally with mounted volumes for /dashboards, /datasources. But how about this configuration here?

**Reply by sbatururimi** [reply]
I answered to myself. To allow the persistence of datasources/dashboards added from UI, then add this to the values.yaml
```
grafana:
  persistence:
    enabled: true
    type: sts
    storageClassName: "longhorn"
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  # Configuring grafana to run behind a proxy under a subpath
  grafana.ini:
  ....
```
