### DISCUSSION TITLE
docs/sso/

### DISCUSSION THREAD

**Discussion by giscus** [ricsanfre/pi-cluster#369] [Announcements]
# docs/sso/

How to configure Single-Sign-On (SSO) in our Pi Kubernetes cluster.

https://picluster.ricsanfre.com/docs/sso/

**Comment by i5Js** [comment]
Interesting: Following it, I'm getting the following error, after login to the oauth2 console:

`Error redeeming code during OAuth2 callback: token exchange failed: oauth2: "unauthorized_client" "Invalid client or Invalid client credentials"`

However, if I disable "client authentication", I can login, but getting a 404 error:

```
10.244.7.215:42592 - 39395285-dd23-4475-b516-89a65da11707 - <user_email> [2024/03/30 14:46:19] [AuthSuccess] Authenticated via OAuth2: Session{email:user_email user:ce458eac-2a49-4a80-aa54-bb66ef545aad PreferredUsername:<user> token:true id_token:true created:2024-03-30 14:46:19.212878477 +0000 UTC m=+2760.130704669 expires:2024-03-30 14:51:19.189199437 +0000 UTC m=+3060.107025628 groups:[role:editor role:viewer role:offline_access role:admin role:uma_authorization role:default-roles-home role:account:manage-account role:account:manage-account-links role:account:view-profile]}
10.244.7.215:42592 - 39395285-dd23-4475-b516-89a65da11707 - - [2024/03/30 14:46:19] proxy.home.dominio.com GET - "/oauth2/callback?state=LCZx-8ct628slwX9Tgi6D9_vHIvK6TOWSTiuR1F7ImU%3A%2F&session_state=0d2be827-3d06-41b0-be04-7eca54adf6a7&iss=https%3A%2F%2Fsso.home.dominio.com%2Frealms%2Fhome&code=b3fb1b30-a272-4d1f-8e43-bedb35fd1680.0d2be827-3d06-41b0-be04-7eca54adf6a7.bebb575b-cd59-4822-a2fb-7d2fe70f0731" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15" 302 24 0.151
10.244.7.215:42592 - 16314e6e-8182-4044-9c54-33e6aca8756a - user_email[2024/03/30 14:46:19] proxy.home.dominio.com GET - "/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15" 404 19 0.002
```

**Reply by ricsanfre** [reply]
Client authentication has to be enabled. Otherwise, the client credentials are not created. Once the client is added to keycloak its client credentials: client_id and client_secret need to be used in the configuration: oauth2-proxy config.

**Comment by i5Js** [comment]
Hello Ricardo, thanks, 

But I don't think I have understood it. I have created a user and a password in keycloak and I'm using that credentials to login to oauth2. am I doing wrong?. I mean, when I login to proxy.home.dominio.com it has for user and a password. What should I use ?

**Reply by ricsanfre** [reply]
Yes, to login you should use the user/password you created in keycloak. 

But for configuring proxy-oauth2 as keycloak client, you need to use the client credentials (app credentials) These credentials can be obtained from https://picluster.ricsanfre.com/docs/sso/#configure-oauth2-proxy-client step 2.
Those credentials have to be used when deploying proxy-oauth2 helm chart (config.clientID and config.clientSecret)

```yml
config:
  # Add config annotations
  annotations: {}
  # OAuth client ID
  # Follow instructions to configure Keycloak client
  # https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#keycloak-oidc-auth-provider

  # Oauth2 client configuration. From Keycloak configuration
  clientID: "oauth2-proxy"
  clientSecret: "supersecreto"
```
