### ISSUE TITLE
Longhorn UI issues

### ISSUE THREAD

**Issue by ricsanfre** [ricsanfre/pi-cluster#25]
## Issue Description

After configuring a backup target (Minio S3 server), Longhorn UI options for taking volumes backup/snapshots appear as disabled.

**Comment by ricsanfre** [comment]
It could be related to the known issue with Longhorn UI when it is behind Traefik 2.x Ingress controller.

See Longhorn documentation about this [issue](https://longhorn.io/kb/troubleshooting-traefik-2.x-as-ingress-controller/)

**Comment by ricsanfre** [comment]
Including Traefik middleware specified in the documentation solves the issue.

```yml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: svc-longhorn-headers
  namespace: longhorn-system
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
```
