### ISSUE TITLE
Vault automatic unseal script SKIP_TLS_VERIFY

### ISSUE THREAD

**Issue by bpartin2009** [ricsanfre/pi-cluster#261]
/etc/vault/vault-unseal.sh for Vault has variable SKIP_TLS_VERIFY set to false by default. When self-signed cert is used, users must flip value to true in order to get vault to unseal using script and service. Otherwise script stays in infinite loop.

**Comment by ricsanfre** [comment]
This environment variable is controlled by one of the variables in [`ricsanfre.vault` Ansible's role](https://github.com/ricsanfre/ansible-role-vault) used to deploy Vault. The behaviour of the vault installation can be set in playbooks variables file `ansible/var/picluster.yml`. Setting`tls_skip_verify` variable to true fixes this issue.

```yml
#######################
# Vault configuration
#######################

vault_hostname: "vault.picluster.ricsanfre.com"
vault_version: 1.15.4

vault_dns: "{{ vault_hostname }}"
vault_enable_tls: true
custom_ca: false
vault_init: true
vault_unseal: true
vault_unseal_service: true
tls_skip_verify: false
```
