### ISSUE TITLE
Prometheus: Add Velero metrics

### ISSUE THREAD

**Issue by ricsanfre** [ricsanfre/pi-cluster#28]
## Enhancement Request

Adding Prometheus monitoring of Velero
.
## Implementation details

Velero helm chart has already Prometheus metrics active and it can be configured  for creating Prometheus  ServiceMonitor resource
From values.yml file:

```yml
# Settings for Velero's prometheus metrics. Enabled by default.
metrics:
  enabled: true
  scrapeInterval: 30s
  scrapeTimeout: 10s

  # service metdata if metrics are enabled
  service:
    annotations: {}
    labels: {}

  # Pod annotations for Prometheus
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"

  serviceMonitor:
    enabled: false
    additionalLabels: {}
    # ServiceMonitor namespace. Default to Velero namespace.
    # namespace:

```
