### ISSUE TITLE
Error deploying Metal LB version 0.13

### ISSUE THREAD

**Issue by ricsanfre** [ricsanfre/pi-cluster#54]
Deployment of Metal LB helm chart failed with message:
"Starting from v0.13.0 configInline is no longer supported. Please see https://metallb.universe.tf/#backward-compatibility".

The values.yml just configured MetalLB in L2 mode and assign a specific address pool:

```yml
  configInline:
    address-pools:
      - name: default
          protocol: layer2
          addresses:
            - 10.0.0.100-10.0.0.200
```

According to [metallb documentation](https://metallb.universe.tf/configuration/) some Kuberentes resources must be created to achieve the same effect.
Create a pool:
```yml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
```
Announce the IP pool using L2 protocol
```yml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
```
```
