### ISSUE TITLE
Memory footprint optimization

### ISSUE THREAD

**Issue by ricsanfre** [ricsanfre/pi-cluster#63]
Right now the PODs consuming the most resources are ES, Kibana and  Prometheus:

**Top PODs by memory**

```shell
kubectl top pods -A --sort-by='memory'
NAMESPACE            NAME                                                        CPU(cores)   MEMORY(bytes)   
k3s-logging          efk-es-default-0                                            165m         1432Mi          
k3s-monitoring       prometheus-kube-prometheus-stack-prometheus-0               335m         1168Mi          
k3s-logging          efk-kb-66f7cdc8bd-hc4mb                                     222m         544Mi           
k3s-monitoring       kube-prometheus-stack-grafana-645d765844-m4q5r              55m          207Mi           
k3s-logging          fluentd-69bff468c6-f9dgc                                    37m          133Mi           
linkerd              linkerd-destination-787d745598-jh6pj                        9m           69Mi            
longhorn-system      longhorn-manager-wmpx4                                      32m          64Mi            
longhorn-system      longhorn-manager-wmpj8                                      20m          62Mi            
longhorn-system      longhorn-manager-r22m9                                      27m          57Mi            
velero-system        velero-574c749cb6-tlwwl                                     4m           52Mi            
certmanager-system   certmanager-cert-manager-cainjector-78cd7b475-qc7vm         3m           50Mi            
longhorn-system      instance-manager-r-5be28d03                                 34m          50Mi            
longhorn-system      instance-manager-r-d15d9bab                                 33m          49Mi  
```

**Top PODs by cpu**

```shell
kubectl top pods -A --sort-by='cpu'
NAMESPACE            NAME                                                        CPU(cores)   MEMORY(bytes)   
k3s-monitoring       prometheus-kube-prometheus-stack-prometheus-0               236m         1199Mi          
k3s-logging          efk-kb-66f7cdc8bd-hc4mb                                     226m         544Mi           
k3s-logging          efk-es-default-0                                            144m         1434Mi          
longhorn-system      instance-manager-e-6cc59123                                 81m          30Mi            
longhorn-system      instance-manager-e-aa8e1208                                 67m          28Mi            
longhorn-system      instance-manager-r-04a02b6c                                 36m          38Mi            
longhorn-system      instance-manager-r-d15d9bab                                 34m          48Mi            
longhorn-system      instance-manager-r-5be28d03                                 33m          50Mi            
longhorn-system      longhorn-manager-wmpx4                                      29m          65Mi            
k3s-logging          fluentd-69bff468c6-f9dgc                                    28m          133Mi           
kube-system          metrics-server-668d979685-rdgcn                             25m          23Mi            
k3s-monitoring       kube-prometheus-stack-grafana-645d765844-m4q5r              24m          203Mi           
longhorn-system      longhorn-manager-wmpj8                                      24m          64Mi      
```

**Some changes to try**
- [x] For ES/Kibana try to adjust the ammount of JVM heap assigned following the procedure in the documentation (https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html).
- [x] For Prometheus, increase scraping interval of Linkerd metrics, currently 10 seconds to the default 30 sg.
- [x] Review metrics: remove duplicates

**Comment by ricsanfre** [comment]
## About linkerd grafana dashboards

Grafana dashboards are using Prometheus' irate function using a interval of 30sg (`irate(<metric>)[30sg]`). [`irate`](https://prometheus.io/docs/prometheus/latest/querying/functions/#irate) function calculates the per-second instant rate of increase of the time series taking only the last samples in the interval. This is not possible if the scrape interval is increase to 30sg.

Dashboards need to be modified. Maybe Grafana's variable [`$__rate_interval`](https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/)  can be used here.

**Comment by ricsanfre** [comment]
## Applying resource limits to ElasticSearch

According to [ECK documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html), "The heap size of the JVM is automatically calculated based on the node roles and the available memory. The available memory is defined by the value of `resources.limits.memory` set on the elasticsearch container in the Pod template, or the available memory on the Kubernetes node is no limit is set"

By default, the resources.limits.memory for ElasticSearch is 2GB

Reducing the limit to 1GB
```yml
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: efk
  namespace: k3s-logging
spec:
  version: 8.1.3
  http:    # Making elasticsearch service available from outisde the cluster
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: longhorn

      podTemplate:
        spec:
          # Limiting Resources consumption
          containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 1Gi
              limits:
                memory: 1Gi

```

The results is that elasticsearch memory consumption is reduced by 500Mb

```shell
kubectl top pods -A --sort-by='memory'
NAMESPACE            NAME                                                        CPU(cores)   MEMORY(bytes)   
k3s-monitoring       prometheus-kube-prometheus-stack-prometheus-0               316m         1278Mi          
k3s-logging          efk-es-default-0                                            2653m        830Mi           
k3s-logging          efk-kb-66f7cdc8bd-hc4mb                                     436m         540Mi           
k3s-monitoring       kube-prometheus-stack-grafana-645d765844-m4q5r              22m          193Mi           
k3s-logging          fluentd-69bff468c6-f9dgc                                    88m          136Mi           
linkerd              linkerd-destination-787d745598-jh6pj                        16m          77Mi            
longhorn-system      longhorn-manager-wmpj8                                      73m          68Mi            
longhorn-system      longhorn-manager-wmpx4                                      55m          65Mi            
longhorn-system      longhorn-manager-r22m9                                      34m          60Mi            
k3s-monitoring       kube-prometheus-stack-operator-56d866647d-xrv9r             6m           55Mi            
longhorn-system      instance-manager-r-d15d9bab                                 165m         54Mi            
velero-system        velero-574c749cb6-tlwwl                                     30m          51Mi        
```
