### ISSUE TITLE
K3S emitting duplicated metrics in all endpoints (Api server, kubelet, kube-proxy, kube-scheduler, etc)

### ISSUE THREAD

**Issue by ricsanfre** [ricsanfre/pi-cluster#67]
## Bug Description

[Kuberentes Documentation - System Metrics](https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/) details which Kubernetes components expose metrics in Prometheus format:

These components are:

- kube-controller-manager (exposing `/metrics` endpoint at TCP 10257)
- kube-proxy (exposing `/metrics` endpoint at TCP 10249)
- kube-apiserver (exposing `/metrics` at Kubernetes API port)
- kube-scheduler (exposing `/metrics` endpoint at TCP 10259)
- kubelet (exposing `/metrics`,  `/metrics/cadvisor`, `/metrics/resource` and `/metrics/probes` endpoints at TCP 10250)

K3S distribution has a special behavior since in each node only one process is deployed ( `k3s-server` running on master nodes or `k3s-agent` running on worker nodes) with all k8s components sharing the same memory.

K3s is emitting the same metrics, from all k8s components deployed in the node, at all '/metrics' endpoints available (api-server, kubelet (TCP 10250), kube-proxy (TCP 10249), kube-scheduler (TCP 10251), kube-controller-manager (TCP 10257). Thus, collecting from all port produces metrics duplicates.

kubelet additional metrics (endpoints `/metrics/cadvisor`, `/metrics/resource` and `/metrics/probes`) are only available at TCP 10250.

Enabling the scraping of all different metrics TCP ports (kubernetes components) causes the ingestion of duplicated metrics. Duplicated metrics in Prometheus need to be removed in order to reduce memory and CPU consumption.

## Context Information

As stated in issue #22, there was a known issue in K3S: https://github.com/k3s-io/k3s/issues/2262, where duplicated metrics are emitted by the three components (kube-proxy, kube-scheduler and kube-controller-manager).
The proposed solution by Rancher Monitoring(https://github.com/k3s-io/k3s/issues/2262), was to avoid the scrape of duplicated metrics and activate only the service monitoring of one of the components. (i.e. kube-proxy). 
That solution was implemented (see https://github.com/ricsanfre/pi-cluster/issues/22#issuecomment-986224709) and it solved the main issue (out-of-memory).

Endpoints currently being scrapped by Prometheus are
- api-server (TCP 6553)
- kubelet (TCP 10250)
- kube-proxy (TCP 10249)

## Duplicated metrics

After deeper analysis on the metrics scrapped by Prometheus, it is clear that K3S is emitting duplicated metrics in all endpoints.

Example 1: API-server metrics emitted by kube-proxy, kubelet and api-server endpoints running on master server

<img width="610" alt="Capture" src="https://user-images.githubusercontent.com/84853324/186138699-7d6d7956-1703-4116-80ae-f2392ac40761.PNG">

Example 2: kubelet metrics emitted by kube-proxy, kubelet and api-server

![image](https://user-images.githubusercontent.com/84853324/186142173-7f119331-07f5-4f30-b792-5e861cf7aa40.png)

Example3: kubepoxy metrics: `kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.001"}`

![image](https://user-images.githubusercontent.com/84853324/186144430-77ea1b56-ee15-4e4b-9d20-46bf937e8738.png)

**Comment by ricsanfre** [comment]
## How to fetch metrics from kubernetes components using https endpoints.

The procedure described here https://github.com/SUSE/doc-caasp/issues/166#issuecomment-476191064 can be used to manually query https metrics endpoints. Most recent versions of Kubernetes are moving all metrics endpoint to use https

**Comment by ricsanfre** [comment]
## Possible solution.
Enabling only monitoring of kubelet endpoints (TCP port 10250), so all metrics can be collected. Remove from kube-prometheus-stack the monitoring of `apiserver` and `kubelet`, and create a single ServiceMonitor configuration for scraping all metrics from port TCP 10250, including all relabeling rules defined within kube-prometheus-stack ServiceMonitor objects

```yml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: k3s-monitoring
  namespace: monitoring
spec:
  endpoints:
  # /metrics endpoint
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    metricRelabelings:
    # apiserver
    - action: drop
      regex: apiserver_request_duration_seconds_bucket;(0.15|0.2|0.3|0.35|0.4|0.45|0.6|0.7|0.8|0.9|1.25|1.5|1.75|2|3|3.5|4|4.5|6|7|8|9|15|25|40|50)
      sourceLabels:
      - __name__
      - le
    
    port: https-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  # /metrics/cadvisor
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    metricRelabelings:
    - action: drop
      regex: container_cpu_(cfs_throttled_seconds_total|load_average_10s|system_seconds_total|user_seconds_total)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_fs_(io_current|io_time_seconds_total|io_time_weighted_seconds_total|reads_merged_total|sector_reads_total|sector_writes_total|writes_merged_total)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_memory_(mapped_file|swap)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_(file_descriptors|tasks_state|threads_max)
      sourceLabels:
      - __name__
    - action: drop
      regex: container_spec.*
      sourceLabels:
      - __name__
    - action: drop
      regex: .+;
      sourceLabels:
      - id
      - pod
    path: /metrics/cadvisor
    port: https-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    # /metrics/probes
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    path: /metrics/probes
    port: https-metrics
    relabelings:
    - action: replace
      sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
```

**Comment by ricsanfre** [comment]
Final solution setting job label to "kubelet" for all metrics scrapped for k3s components through kubelet port. 
This way only a few dashboards need to be changed. (kube-proxy, kube-controller-manager and apiserver).

Selecting a different name such as "k3s" (initial proposed solution) makes that all default kube-prometheus-stack dashboards using kubelet metrics (container metrics), need to be updated. For example: The following dashboards use "job=kubelet" when filtering the metrics.
 Kubernetes - Compute Resources /Cluster
 Kubernetes - Compute Resources / Namespace (Pods)
 Kubernetes - Compute Resources / Namespace (Workloads)

**Comment by sherif-fanous** [comment]
@ricsanfre First this repo and the accompanying website are awesome. Thanks for your efforts.

Regarding this issue I want to let you know that I've solved it in a little bit of a different manner that ensures that the `kube-prometheus-stack` chart is still creating the rules and grafana dashboards thus eliminating the need to manually handle this step.

So instead of disabling all the components in the Helm chart I actually keep them updated but instruct all but the `kubelet` `ServiceMonitor` to drop all the metrics they scrape

e.g. This is how I defined my `kubeApiServer` section in my values.yaml file

```yaml
kubeApiServer:
  serviceMonitor:
    metricRelabelings:
      - action: drop
        regex: .*
        sourceLabels:
          - __name__
```

I have a similar snippet for `kubeControllerManager`, `kubeProxy`, and `kubeScheduler`

With this the Chart is still creating the rules and dashboards without ingesting duplicate metrics. Only metrics from the `kubelet` are kept.

Now the rules and dashboards created by the chart refer to a job that needs to be replaced with `kubelet` so I make use of a very simple Argo CD [Config Management Plugin](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#using-environment-variables-in-your-plugin).

In the `init` command I use `helm template` to generate the templates and then in the `generate` command I run a couple of `sed` commands that replace the job values with `kubelet`.

The end result is

1. All rules and dashboards are automatically created by the chart with the correct job values
2. Only 1 copy of metrics is ingested (The ones from the `kubelet` endpoint)

The only drawback is that although Prometheus doesn't ingest duplicate metrics it still ends up scraping multiple end points and dropping the metrics from these endpoints which of course means relatively higher CPU and memory usage.
