### ISSUE TITLE
Ansible: Encrypt passwords and keys used in playbooks with Ansible Vault

### ISSUE THREAD

**Issue by ricsanfre** [ricsanfre/pi-cluster#77]
## Enhancement Request

Encrypt all passwords/keys that currently and stored in plain-text within ansible variables.

Use Ansible Vault capability for that.

## References

- [Ansible Documentation- Encrypting content with Ansible Vault](https://docs.ansible.com/ansible/latest/user_guide/vault.html)
- [Ansible Best practices: Tip for variables and vaults](https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#tip-for-variables-and-vaults)
- [Secure group variables with Ansible vault](https://duffney.io/secure-group-variables-with-ansible-vault/)
- [How to include variables from ansible vault file](https://www.toptechskills.com/ansible-tutorials-courses/ansible-include-import-variables-tutorial-examples/#how-to-include-variables-from-an-ansible-vault-file)

**Comment by ricsanfre** [comment]
## Solution implemented

1) Include all secrets, keys in a specific var yaml file: `vautl.yml` located in `vars` directory

```yml
  ---
  # Encrypted variables - Ansible Vault
  vault:
    # SAN
    san:
      iscsi:
        node_pass: s1cret0
        password_mutual: 0tr0s1cret0
    # K3s secrets
    k3s:
      k3s_token: s1cret0
    # traefik secrets
    traefik:
      basic_auth_passwd: s1cret0
    # Minio S3 secrets
    minio:
      root_password: supers1cret0
      longhorn_key: supers1cret0
      velero_key: supers1cret0
      restic_key: supers1cret0
    # elastic search
    elasticsearch:
      admin_password: s1cret0
    # Fluentd
    fluentd:
      shared_key: s1cret0
    # Grafana
    grafana:
      admin_password: s1cret0
  ```

2) Encrypt the file with Ansible vault

    ```shell
    ansible-vault encrypt vault.yml
    ```
    Provide ansible vault password to encrypt the file.

   The file can be decrypted using the following command

   ```shell
   ansible-vault decrypt vault.yml
   ```

4) Reference the vault variables in playbooks, group_vars, etc.

   For example in: k3s_cluster group variables.
  
   ```yml
    # k3s shared token
     k3s_token: "{{ vault.k3s.k3s_token }}"
   ```
   All referenced variables that are encrypted by ansible vault will have belong to `vault` yaml dictionary, so they can be clearly identified and their values located in `vault.yml` file.

5) Include task to load vault variables file in each playbook's pre-task section:

    ```yml
    - name: my_playbook
      hosts: my_server
      pre_tasks:
        - name: Include vault variables
          include_vars: "vars/vault.yml"
          tags: ["always"]
      roles:
      ....
    ```
6) Execute ansible playbooks with `--ask-vault-pass` argument, so the password used to encrypt vault file can be provided when starting the playbook.

    ```shell
    ansible-playbook my-playbook.yml --ask-vault-pass
    ```
