### ISSUE TITLE
Extend validity period of Linkerd-identity-issuer certificate and make it configurable

### ISSUE THREAD

**Issue by ricsanfre** [ricsanfre/pi-cluster#85]
Linkerd-identity-issuer certificate generated by CertManager has a duration 48h and it will be renewed 25h before expiration.

This anchor certificate is used to issue Linkerd-proxy's mTLS cerificates which are rotated every 24 hours.

```yml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 48h
  renewBefore: 25h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
```
With this configuration anchor certificate is renewed every day, forcing all Linkerd-proxy certificates to be also renewed. So every linkerd-proxy certificate will need to be rotated twice every day, which does not make sense.

This short validity periods is the cause of the problems I am facing with linkerd not working properly, when starting pi-cluster after a couple of days shutdown.

Extend validity period of issuer certificate and make it configurable in Ansible Playbook. Installation using linkerd command line, creates a issuer certificate valid for 1 year.
